### ISSUE TITLE
Віджет  сумісності не вміє обробляти множинні вхідні значення

### ISSUE THREAD

**Issue by AdriandeCita** [webdoky/yari-ports#58]
![image](https://user-images.githubusercontent.com/11510394/223678506-1ad5f14d-1ca2-44d5-9c46-2077916a9543.png)

https://webdoky.org/uk/docs/Web/JavaScript/Guide/Modules/#sumisnist-iz-brauzeramy

**Comment by undead404** [comment]
Дублікат
